image: python:3.6
pipelines:
  default:
    - step:
        script:
          - python -m pip install -r requirements.txt
          - python -m pip install pytest pylint
          - python setup.py build_ext -i
          - python -m pytest -v beancount
          - make lint
